### PR TITLE
translate missing german as good as possible

### PR DESCRIPTION
**Pull request by ravermeister**
Translate missing German Strings as good as possible

### CODE REVIEW

**Comment by hgouraud** [comment]
@ravermeister
Jonny, thanks for your input, but next time, keep the structure of the file as is!
It needs to have the format
```
    message
l1: translation l1
l2: translation l2

```
with 4 spaces (no tabs!) before the message name and blank lines between message blocks!!
I have reworked what you gave me to inject it in `lex_utf8`, but I have a few more entries I added this morning that are now in a new version of `missing/lex_de.txt`.

Thanks for your help

**Comment by hgouraud** [comment]
@ravermeister
I have added, in branch gwsetup-1, bin/setup/lang/missing a list of missing translations for gwsetup.
Same format as for the main lexicon.
Thanks for your help

**Comment by ravermeister** [comment]
Hi, no problem I'll leave the format. I was confused of the newlines, and the fact that `en: message` and `fr: message` had another format:
```
de:

    a brother-in-law/brothers-in-law/a sister-in-law/sisters-in-law
en: one brother-in-law/brothers-in-law/one sister-in-law/sisters-in-law
fr: un beau-frère/beaux-frères/une belle-sœur/belles-sœurs
```

think I now understand after translation it should look like
```
    a brother-in-law/brothers-in-law/a sister-in-law/sisters-in-law
de: german translation
en: one brother-in-law/brothers-in-law/one sister-in-law/sisters-in-law
fr: un beau-frère/beaux-frères/une belle-sœur/belles-sœurs
```
correct? in this case I think the base message is missing in some lines in the `tools` branch file `hd/lang/lex_utf8.txt`: [32](https://github.com/hgouraud/geneweb/blob/f38625702ce7e8546c48ac9e6d5c8a38db4ad234/hd/lang/lex_utf8.txt#L32) [36](https://github.com/hgouraud/geneweb/blob/f38625702ce7e8546c48ac9e6d5c8a38db4ad234/hd/lang/lex_utf8.txt#L36) [45](https://github.com/hgouraud/geneweb/blob/f38625702ce7e8546c48ac9e6d5c8a38db4ad234/hd/lang/lex_utf8.txt#L45) 
no problem. I'll check the new file.

many greetings
Jonny

**Comment by hgouraud** [comment]
yes, you have the right format

No, it is on a different branch, specific to gwsetup!!
branch: setup-1

ooups! I had forgotten to include the missing folder in the branch! corrected.

**Pull request merged**
