### PR TITLE
Remove perso_module_* from a.gwf

### PR DESCRIPTION
**Pull request by michelmno**
Remove perso_module_* from a.gwf

This is to complete PR #1784 and
cid 11f0c8739 "perso_modules .gwf -> perso_utils"

Question to @hgouraud: Where are we supposed to place the additional module ?
I tried with "perso_module_z=arbre_vertical.txt" in gwf but the include failed:
`%include.modules/arbre_vertical.txt?`

### CODE REVIEW

**Comment by hgouraud** [comment]
in your .gwf file, define
```
perso_module_w=file_1
perso_module_x=file_2
perso_module_z=file_3
```
`file_1/2/3.txt` should be in `bases/etc/mybase/modules` (base specific), `bases/etc/mybase/modules` (all bases), or `gw/etc/modules` (the distribution), the search being in that order.

**Comment by hgouraud** [comment]
in your trial, you should remove the `.txt` extension

**Comment by michelmno** [comment]
I updated comments in a.gwf as per @hgouraud suggestion.
and added a commit to add related tests in run-GW-test.sh

**Comment by michelmno** [comment]
This  run-GW-test.sh update allow to identify errors in two modules as per following trace;
I did not tried to understand failure, that concern
[hd/etc/modules/arbre_h6.txt](https://github.com/hgouraud/geneweb/blob/fix-home/hd/etc/modules/arbre_h6.txt) and
[hd/etc/modules/arbre_hi.txt](https://github.com/hgouraud/geneweb/blob/fix-home/hd/etc/modules/arbre_hi.txt)
```
$./run-GW-test.sh -c
history_diff=yes not set in /home/michel/work/geneweb/local/bases/testbasefusionnee.gwf
three history_diff related commands are not tested.
authorized_wizards_notes=yes not set in /home/michel/work/geneweb/local/bases/testbasefusionnee.gwf
three wizards notes related commands are not tested.
test gw.01e218982/etc/modules/arbre_h6.txt as p_mod=z1
  var errors_list = "\u{000A}Unbound variable(s): %else?,%end?. ";
test gw.01e218982/etc/modules/arbre_hi.txt as p_mod=z1
  var errors_list = "\u{000A}Unbound variable(s): %I?. ";
/tmp/gwd_cgi_tst_error.log reported traces (empty if no failure):
[2024-06-02 15:33:21]: WARNING ******** Compute 6 × 18 table ********
[2024-06-02 15:33:22]: WARNING ******** Compute 6 × 18 table ********
at least 2 detected error(s).
```

**Comment by hgouraud** [comment]
Je regarde dans la soirée.

**Pull request merged**
