### PR TITLE
test/run-GW-test.sh Add debug opt & tests based on anctree.txt

### PR DESCRIPTION
**Pull request by michelmno**
* Debug option allow to print out url for manual usage.
* Report nb of errors if any, on perso_modules tests.
* Trial adding more tests as per hd/etc/anctree.txt

@hgouraud  any comments ?

### CODE REVIEW

**Comment by michelmno** [comment]
With new test_gwu.sh  I identified lost divorced date in family line,
Why to make such a change in PR  https://github.com/geneweb/geneweb/pull/1784 cid cdec8ac12 ?
```
-fam Galichet lolo +1840 #ms inventé -1844 femme1 prenom1 #src inventé 1818 od
+fam Galichet lolo +1840 #ms inventé femme1 prenom1 #src inventé 1818 od
```

**Comment by hgouraud** [comment]
with this PR, divorce and separation are handled as family events with associated date, note and source.
the divorce date is kept in the fevt section rather that in the fam section.

**Comment by michelmno** [comment]
> with this PR, divorce and separation are handled as family events with associated date, note and source. the divorce date is kept in the fevt section rather that in the fam section.

The divorce was already kept before in fevt, like mariage or death since v7.0 (duplication of information)
so why to remove from fam section the divorce date and not the marriage  with that change ?
Anyway you have to keep internally the support of divorce in fam section for old_gw support.

**Comment by hgouraud** [comment]
yes, old_gw maintains divorce date in .gw file
as much as possible, we should avoid duplication of information in the .gw file (this is not the case today)
in a future PR, we should remove from the fam line info which is also reported in the fevt section.
idem for birth, baptism, death, and burial!

**Comment by hgouraud** [comment]
I believe that the tests you added from anctree.txt are partially covered by the tests with p_mod=a1/2/3/4 and p_mod=h1/2/3/4/5. To be verified!!

**Pull request merged**
