### PR TITLE
add missing bvars in a.gwf and other commits

### PR DESCRIPTION
**Pull request by michelmno**
list of commits (reversed order)
* Add few missing bvars in a.gwf (step1)
* Comment out max_anc* max_desc* bvars in a.gwf
* Replace %bvar.static_path; by %static_path; (step2)
* Put back home buttons on place_v7

@hgouraud , @a2line are you OK to merge them in hgouraud/fix-rl ?
or do you want me to do some changes ?

### CODE REVIEW

**Comment by a2line** [comment]
We wanted to switch the condition for compilation_time but I forgot to do the renaming after working on bug icon. We want it active by default at last for beta phase to get rid of a maximum of bugs. I have switched “show_compilation_time” to "hide_compilation_time=yes" so if not present in gwf this is printed. If you can just remove cid 688635b the rest is good for me.

**Comment by a2line** [comment]
« The "static_path" parameter in gwf has been depreciated and is now set from the GW_STATIC_PATH environment variable. » is perhaps easier to understand (gwf parameter is a multiple times in CHANGES).

**Comment by michelmno** [comment]
> « The "static_path" parameter in gwf has been depreciated and is now set from the GW_STATIC_PATH environment variable. » is perhaps easier to understand (gwf parameter is a multiple times in CHANGES).

suggestion handled in last PR update.

**Comment by michelmno** [comment]
> We wanted to switch the condition for compilation_time but I forgot to do the renaming after working on bug icon. We want it active by default at last for beta phase to get rid of a maximum of bugs. I have switched “show_compilation_time” to "hide_compilation_time=yes" so if not present in gwf this is printed. If you can just remove cid [688635b](https://github.com/hgouraud/geneweb/commit/688635b36adb56c28ce916e5dfc261ae4fa111f3) the rest is good for me.

* related commit removed in last PR update.
* why to refer to a "hide_compilation_time"  rather than a "hide_query_time" ?
  there is no compilation process at that time, only a query.
* In your cid d3c05c9e1 you forgot to add related parameter in a.gwf, do you want me to do it ?

**Comment by hgouraud** [comment]
yes please.
I will merge after (busy chasing some other detail bugs)

**Comment by michelmno** [comment]
> yes please. I will merge after (busy chasing some other detail bugs)

just pushed PR update with show_compilation_time in a.gwf

**Comment by a2line** [comment]
About bvar in `a.gwf`: be carefull for what you call "booleans" that are not real ones, when you write “default no” (for `hide_compilation_time`) it could be misleading because there is no template nor .ml interpretation of that “no”. It is the same for a lot of other bvars where we only test one condition. We should write “shown by default” instead of “default no” that could lead some people to write as it is and won’t understand why it’s not working.

I agree I was wrong using the world “compilation”. What about `hide_qtime_bugs`?

**Comment by michelmno** [comment]
> About bvar in `a.gwf`: be carefull for what you call "booleans" that are not real ones, when you write “default no” (for `hide_compilation_time`) it could be misleading because there is no template nor .ml interpretation of that “no”. It is the same for a lot of other bvars where we only test one condition. We should write “shown by default” instead of “default no” that could lead some people to write as it is and won’t understand why it’s not working.

OK, I will update the commits of this PR

> 
> I agree I was wrong using the world “compilation”. What about `hide_qtime_bugs`?

OK for me,  I could do the change in this PR in a.gwf and in code itself.

**Comment by michelmno** [comment]
> > About bvar in `a.gwf`: be carefull for what you call "booleans" that are not real ones, when you write “default no” (for `hide_compilation_time`) it could be misleading because there is no template nor .ml interpretation of that “no”. It is the same for a lot of other bvars where we only test one condition. We should write “shown by default” instead of “default no” that could lead some people to write as it is and won’t understand why it’s not working.
> 
> OK, I will update the commits of this PR
> 
> > I agree I was wrong using the world “compilation”. What about `hide_qtime_bugs`?
> 
> OK for me, I could do the change in this PR in a.gwf and in code itself.

done with last PR update

**Comment by a2line** [comment]
Ok. Thank you. I think we can merge this work Henri!

**Comment by hgouraud** [comment]
@A2, is this PR mergeable, or have you made modifications directly in fix-rl?

**Comment by michelmno** [comment]
> @a2, is this PR mergeable, or have you made modifications directly in fix-rl?

to be sure, I just rebased on top of fix-rl head (commit 53fa98d06  add more tests in test_sosa.ml)
so ready to be merged there.

**Comment by a2** [comment]
I think you meant to mention @a2line instead

**Comment by hgouraud** [comment]
C'est la même parsonne!!

**Comment by hgouraud** [comment]
PR mergée dans fix-rl.
Attention!! le fichier place_v7 a été renommé place en remplacement de l'ancien place!

**Pull request merged**
