### PR TITLE
Updating lex_co.txt with missing Corsican strings

### PR DESCRIPTION
**Pull request by Patriccollu**
Hello Henri,

I just completed the translation in **Corsican** of all the strings found in file `lex_co.txt`.

The updated version committed in this PR now contains Corsican translation in addition to English and French ones.

Regarding my two previous questions in #1 , I put the following strings:

	co: Connex
	co: Consang
	co: zitelli - famiglie.
	co: genitori - famiglie.
	co: testimoni - « fevents ».
	co: divorziu - matrimoniu.
	co: famiglie - persone.
	co: NBDS - persone.
	co: genitori - persone.
	co: testimoni - « pevents ».

	co: Quand’una persona hè nata menu di <num> anni fà, ùn face micca parte di l’espurtazione for di s’ella hè publica.<br> Tutti i sposi è discendenti sò prutetti dinù.

If you give me more details I will be able to modify them if necessary..

Cheers,
Patriccollu.

### CODE REVIEW

**Comment by Patriccollu** [comment]
The second commit is for the two missing strings in file `lex_co.txt` located in `hd/lang/missing/` directory.

**Comment by Patriccollu** [comment]
@hgouraud 
Hello Henri,

I hope that you are well... and had a pleasant Christmas!

Have you had a chance to read my previous comments? Are the two committed members in this PR what you were expecting from me? If not, feel free to tell me and I will be happy to help you.

Cheers,
Patriccollu.

**Comment by hgouraud** [comment]
Until my changes in gwsetup are merged, it will be difficult to merge your updates.I am quite busy moving from one place to another. This will keep me busy for a while, but dont lose hope!!
Cheers

**Comment by Patriccollu** [comment]
@hgouraud 
Hello Henri,

Thanks for your feedback. I understand your concerns regarding gwsetup and my scope was not at all to put some pressure on you! ;-) Good luck for your move and happy New Year's Eve!

Cheers,
Patriccollu.

**Comment by Patriccollu** [comment]
I'm closing this old PR which has been propagated to GeneWeb repository with another PR.

**Pull request closed without merging**
